#========================================
# Bootstrap
#========================================

# Force TPM to install all plugins inside your hidden data directory
set-environment -g TMUX_PLUGIN_MANAGER_PATH "~/.local/share/tmux/plugins/"

# Automatic Bootstrap
set -g @tpm_path "~/.local/share/tmux/plugins/tpm"
run-shell "test ! -d #{@tpm_path} && git clone https://github.com/tmux-plugins/tpm #{@tpm_path} || true"


#========================================
# Plugins List
#========================================
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "rose-pine/tmux"

set -g @plugin "tmux-plugins/tmux-continuum"
set -g @plugin "tmux-plugins/tmux-resurrect"

# Plugin Configuration
set -g @continuum-restore "on"


#========================================
# Keybinds and options
#========================================

# reload config
bind r source-file "$HOME/.config/tmux/tmux.conf" \; display "Config reloaded"

# switch panes with M-hjkl
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R
set -s escape-time 0

# easily toggle synchronize-panes
bind -n M-s setw synchronize-panes

# enable mouse control
set -g mouse off

# don't rename windows automatically
set-option -g allow-rename off

# fixes highlighting issues
set -g default-terminal "tmux-256color"

# cap history limit to prevent crashing during reflows
set -g history-limit 10000

# prevent resize latency when switching panes or windows
set -s escape-time 0

# ensure window resizing targets the most recent attached client cleanly
set-option -g window-size latest

#------------------------------
# Active vs. Inactive Pane Indicators
#------------------------------

# Dim Inactive Panes
set -g window-style 'fg=#908caa,bg=#16141f'
set -g window-active-style 'fg=#e0def4,bg=#191724'

# Clear Active Borders
set -g pane-border-style 'fg=#26233a'
set -g pane-active-border-style 'fg=#ebbcba'

# 3. Clean Border Lines
set -g pane-border-lines heavy

#========================================
# Execution
#========================================

run-shell "#{@tpm_path}/tpm"
