#========================================
# Environment & Custom Plugin Directory
#========================================
set-environment -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.local/share/tmux/plugins/"

# Automatically clone TPM if it's missing
if-shell "test ! -d $HOME/.local/share/tmux/plugins/tpm" \
   "run-shell 'git clone https://github.com/tmux-plugins/tpm $HOME/.local/share/tmux/plugins/tpm'"

#========================================
# Plugins List
#========================================
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "rose-pine/tmux"
set -g @plugin "tmux-plugins/tmux-continuum"
set -g @plugin "tmux-plugins/tmux-resurrect"

set -g @continuum-restore "on"

#========================================
# Keybinds and Options
#========================================
# Reload config
bind r source-file "$HOME/.config/tmux/tmux.conf" \; display "Config reloaded"

# Switch panes with M-hjkl
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Toggle synchronize-panes
bind -n M-s setw synchronize-panes

set -g mouse off
set-option -g allow-rename off
set -g default-terminal "tmux-256color"
set -g history-limit 10000
set -s escape-time 0

set -ag terminal-overrides ",xterm-256color:RGB"
set -g @rose_pine_variant "main"
set -g @rose_pine_host "on"
set -g @rose_pine_user "on"
set -g @rose_pine_directory "on"

# Vi copy-mode → system clipboard
setw -g mode-keys vi
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard"
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -selection clipboard"

# Pass-through for WezTerm image rendering
set -gq allow-passthrough on
set -g visual-activity off

# Enable setting the terminal tab/window title
set -g set-titles on
set -g set-titles-string "#S"

# Automatically renumber remaining windows sequentially when one is closed
set -g renumber-windows on


#------------------------------
# Active vs. Inactive Pane Indicators
#------------------------------

# Full Line Indicators & Border Headers
set -g pane-border-indicators both
set -g pane-border-lines double
set -g pane-border-status top
set -g pane-border-format " #{?pane_active,#[fg=#ebbcba]#[bold] ⏺ #P ,#[fg=#6e6a86] #P } "

# Border Colors
set -g pane-border-style "fg=#26233a"
set -g pane-active-border-style "fg=#ebbcba"

# High-Contrast Text & Background Dimming
set -g window-style "fg=#908caa,bg=#16141f"  # Inactive
set -g window-active-style "fg=#e0def4,bg=#191724"  # Active

#========================================
# Execution
#========================================
run "$HOME/.local/share/tmux/plugins/tpm/tpm"
