# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Source additional files
if [ -d $(dirname $(realpath ${BASH_SOURCE[0]}))/bash.d ]; then
    for d in $(dirname $(realpath ${BASH_SOURCE[0]}))/bash.d/*; do
        . $d
    done
fi
