# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Temporary variables to be unset later
DIRNAME=$(dirname $(realpath ${BASH_SOURCE[0]}))

# Source additional files
if [ -d ${DIRNAME}/bash.d ]; then
    for d in $DIRNAME/bash.d/*; do
        . $d
    done
fi

# Cleanup
unset DIRNAME
