# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Source additional files
if [ -d $(dirname $(realpath ${BASH_SOURCE[0]}))/bash.d ]; then
    for d in $(dirname $(realpath ${BASH_SOURCE[0]}))/bash.d/*; do
        . $d
    done
fi

# >>> mamba initialize >>>
# !! Contents within this block are managed by 'mamba init' !!
export MAMBA_EXE='/home/vchao/.local/bin/micromamba';
export MAMBA_ROOT_PREFIX='/home/vchao/Documents/micromamba';
__mamba_setup="$("$MAMBA_EXE" shell hook --shell bash --root-prefix "$MAMBA_ROOT_PREFIX" 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__mamba_setup"
else
    alias micromamba="$MAMBA_EXE"  # Fallback on help from mamba activate
fi
unset __mamba_setup
# <<< mamba initialize <<<
